<?php

namespace examen\magasinBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * lotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class lotRepository extends EntityRepository
{
    
    public function findBylibelle($libelle) {
        
           $qb=$this->createQueryBuilder('l');
            $qb->where('l.libelle like :libelle ')     
                    ->setParameter('libelle', $libelle);
            return $qb->getQuery()->getResult();
        
    }
}
